therapy_session_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'therapy_user') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'therapy_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'therapy_rag') }}"
      schema: public
      threads: 4
